baseURL = "https://sfedov.com/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Sergey Fedorov · Home Page"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Sergey Fedorov"
  email = "sfedrv@gmail.com"
  description = "Sergey Fedorov"
  bio = "Making the Internet faster.  \nNow: Director of Engineering at Netflix."
  avatar = "img/avatar.jpeg"
  favicon = "img/favicon.ico"
  error404 = "You missed a turn somewhere - there is nothing here."

  [params.contact]
  	linkedin = "https://www.linkedin.com/in/sfedov/"
  	twitter = "https://twitter.com/sfedov"
    github = "https://github.com/sfedr"
    instagram = "https://instagram.com/didnothappen"
    facebook = "https://www.facebook.com/sergey.y.fedorov"
